# Generated by Django 4.0 on 2022-05-02 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('webpath', models.CharField(default='https://img.cster.xyz/litao/default.jpg', max_length=250)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2022, 5, 2, 16, 52, 30))),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('is_online', models.PositiveSmallIntegerField(default=0)),
                ('is_activate', models.PositiveSmallIntegerField(default=1)),
                ('is_show', models.PositiveSmallIntegerField(default=1)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.role')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=200)),
                ('webpath', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('classify', models.CharField(default='', max_length=10)),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('is_show', models.PositiveSmallIntegerField(default=1)),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.user')),
            ],
        ),
    ]
